### PR TITLE
Implement question export/import for LS v4+

### PR DESCRIPTION
**Pull request by gabrieljenik**

### CODE REVIEW

**Comment by gabrieljenik** [comment]
@TonisOrmisson As discussed in the other PR, on top of this we would send more individual features

**Comment by TonisOrmisson** [comment]
thanks for the PR! I did a new release version 1.2.0

**Comment by TonisOrmisson** [comment]
I have not used it for a while, maybe you can tell if your PR could possibly also fix #1 ?

**Comment by gabrieljenik** [comment]
> I have not used it for a while, maybe you can tell if your PR could possibly also fix #1 ?

I think we will on one of our next PRs

**Pull request merged**
