### PR TITLE
Update v5, v6, PHP8

### PR DESCRIPTION
**Pull request by gabrieljenik**
Misc Enhancements:
- Update v5 & v6
- PHP8
- Include Vendor for easier installation

Others:
- FIX: Treatment of empty attributes
- ENH: Include question theme
- ENH: Fix multiline texts and i18n attributes
- Fix import subquestions on LS5
- Fix: Export Order subquestions

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
Thanks. 
A few comments. 
1. you are merging to an old version, you should check your branch against the latest master. I have difficulties understanding what you actually have changed compared to latest version
2. I will not include vendor, sry : ) I think this way of merging the whole dependencies into core code is a bad way to go also for LS. Using dependency links might be an option or if there is some post-install hook for installing plugins via ui

**Comment by gabrieljenik** [comment]
> you are merging to an old version, you should check your branch against the latest master. I have difficulties understanding what you actually have changed compared to latest version

I know. We have accumulated a few changes.
We have created a lib for the plugin and split it in 2, depending on the version.

Also:
- FIX: Treatment of empty attributes :: Empty attributes (empty string) were creating failures.
- ENH: Include question theme :: Question Themes were hard to specify.
- ENH: Fix multiline texts and i18n attributes
- Fix import structure and subquestions on LS5 :: Some adaptations for v5
- Fix: Export Order subquestions

> I will not include vendor, sry : ) I think this way of merging the whole dependencies into core code is a bad way to go also for LS. Using dependency links might be an option or if there is some post-install hook for installing plugins via ui

Understand. Don't agree, but understand :)

**Comment by TonisOrmisson** [comment]
I would appreciate the fixes and enhancements but ...

you really need to merge the master into your code and work out the conflicts. It seems you have fixed some things (eg v4+version stuff) in parallel and It seems reasonable to sync it before making any new/different changes. 

also no way going back to box/spout - its archived, openspout as it is in master is a current replacement and you are better off using that however you implement the plugin.

**Comment by gabrieljenik** [comment]
We will create one PR for each of these enhancements:
- FIX: Treatment of empty attributes :: Empty attributes (empty string) were creating failures.
- ENH: Include question theme :: Question Themes were hard to specify.
- ENH: Fix multiline texts and i18n attributes
- Fix import structure and subquestions on LS5 :: Some adaptations for v5
- Fix: Export Order subquestions

Then you will be able to analyze easier.

**Pull request closed without merging**
